[package]
name = "playground"
version = "0.1.0"
edition = "2021"
description = "A rust playground repository."

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.0"
fern = "0.6.1"
chrono = "0.4.19"

[dev-dependencies]